spring.application.name=userlogin

spring.datasource.url=jdbc:mysql://localhost:3306/User
spring.datasource.username=root
spring.datasource.password=3419

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true